In [4]:
# ==========================================================
# Hands-On #2: Matrix Operations in NumPy
# ==========================================================

import numpy as np
# ==========================================================
# 1. Matrix Creation & Basic Operations
# ==========================================================
print("=" * 60)
print("1. MATRIX CREATION & BASIC OPERATIONS")
print("=" * 60)
A = np.array([[2, 1],
              [0, 3]])
B = np.array([[1, 4],
              [2, 5]])
print("\nMatrix A:")
print(A)
print("\nMatrix B:")
print(B)
# Matrix Addition
print("\nA + B =")
print(A + B)
# Matrix Transpose
print("\nTranspose of A (Aᵀ) =")
print(A.T)

# Matrix Multiplication
print("\nA @ B =")
print(A @ B)

# ==========================================================
# 2. Identity Matrix & Matrix Inverse
# ==========================================================
print("\n" + "=" * 60)
print("2. IDENTITY MATRIX & MATRIX INVERSE")
print("=" * 60)

# Create a 3x3 Identity Matrix
I = np.eye(3)
print("\n3x3 Identity Matrix:")
print(I)
# Matrix for inverse calculation
A = np.array([[2, 1],
              [1, 3]])
print("\nMatrix A:")
print(A)

# Inverse of A
A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)
# Verify A × A_inverse = Identity
print("\nVerification (A @ A_inv):")
print(A @ A_inv)

# ==========================================================
# 3. Solving System of Linear Equations
# ==========================================================

print("\n" + "=" * 60)
print("3. SOLVING Ax = b")
print("=" * 60)

# Equations:
# 2x + y = 5
# x + 3y = 7

A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 7])

# Solve for x
solution = np.linalg.solve(A, b)

print("\nCoefficient Matrix A:")
print(A)
print("\nConstant Vector b:")
print(b)

print("\nSolution [x, y] =")
print(solution)
# Verify solution
print("\nVerification (A @ solution):")
print(A @ solution)

# ==========================================================
# 4. Real-World Exercise:
#    Finding Prices of Three Products
# ==========================================================

print("\n" + "=" * 60)
print("4. REAL-WORLD EXERCISE: PRODUCT PRICING")
print("=" * 60)

"""
Suppose a shop sells:

x = Price of Pen
y = Price of Notebook
z = Price of Marker

Customer Orders:

2 Pens + 1 Notebook + 1 Marker = ₹45
1 Pen + 3 Notebooks + 2 Markers = ₹80
3 Pens + 2 Notebooks + 4 Markers = ₹110

Find individual prices.
"""

# Coefficient Matrix
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [3, 2, 4]
])

# Total bill amounts
b = np.array([45, 80, 110])

# Solve
prices = np.linalg.solve(A, b)

pen_price = prices[0]
notebook_price = prices[1]
marker_price = prices[2]

print("\nCoefficient Matrix:")
print(A)

print("\nBill Amounts:")
print(b)

print("\nCalculated Prices:")
print(f"Pen Price      = ₹{pen_price:.2f}")
print(f"Notebook Price = ₹{notebook_price:.2f}")
print(f"Marker Price   = ₹{marker_price:.2f}")

# Verification
print("\nVerification:")
print("A @ prices =")
print(A @ prices)

print("\nOriginal bill totals:")
print(b)

# ==========================================================
# 5. Summary
# ==========================================================

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)

print("""
✔ Matrix Addition      -> A + B
✔ Matrix Transpose     -> A.T
✔ Matrix Multiplication-> A @ B
✔ Identity Matrix      -> np.eye()
✔ Matrix Inverse       -> np.linalg.inv()
✔ Solve Ax = b         -> np.linalg.solve()

Best Practice:
Use np.linalg.solve() instead of inv(A) @ b
because it is faster, more accurate, and
recommended in scientific computing and ML.
""")

1. MATRIX CREATION & BASIC OPERATIONS

Matrix A:
[[2 1]
 [0 3]]

Matrix B:
[[1 4]
 [2 5]]

A + B =
[[3 5]
 [2 8]]

Transpose of A (Aᵀ) =
[[2 0]
 [1 3]]

A @ B =
[[ 4 13]
 [ 6 15]]

2. IDENTITY MATRIX & MATRIX INVERSE

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A:
[[2 1]
 [1 3]]

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Verification (A @ A_inv):
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]

3. SOLVING Ax = b

Coefficient Matrix A:
[[2 1]
 [1 3]]

Constant Vector b:
[5 7]

Solution [x, y] =
[1.6 1.8]

Verification (A @ solution):
[5. 7.]

4. REAL-WORLD EXERCISE: PRODUCT PRICING

Coefficient Matrix:
[[2 1 1]
 [1 3 2]
 [3 2 4]]

Bill Amounts:
[ 45  80 110]

Calculated Prices:
Pen Price      = ₹8.18
Notebook Price = ₹14.55
Marker Price   = ₹14.09

Verification:
A @ prices =
[ 45.  80. 110.]

Original bill totals:
[ 45  80 110]

SUMMARY

✔ Matrix Addition      -> A + B
✔ Matrix Transpose     -> A.T
✔ Matrix Multiplication-> A @ B
✔ Identity M