In [1]:
import numpy as np
I= np.eye(3)
print("Identity: \n",I)
A= np.array([[2,1],[1,3]])
A_inv = np.linalg.inv(A)
print("A_inv:\n",A_inv)
print("A @ A_inv:\n",A @ A_inv)


Identity: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A_inv:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A @ A_inv:
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
